2024-09-28 20:47:26,566 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7942908605:AAHohHYUAUNBklq0CoY2Drhl6x6jROHWxj8/sendInvoice "HTTP/1.1 400 Bad Request"
2024-09-28 20:47:26,566 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_application.py", line 1335, in process_update
    await coroutine
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/telegram_bot.py", line 54, in buy_stars_yoomoney
    await context.bot.send_invoice(**invoice_params)
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 2748, in send_invoice
    return await super().send_invoice(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 5152, in send_invoice
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TelegramLoginWidget/.pythonlibs/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Currency_total_amount_invalid